# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will generate and upload a dependency graph of a Java project with Gradle for Dependabot to consume

name: Java Dependency Graph with Gradle

on:
  push:
    branches:
      - 'main'

jobs:
  dependency-submission:
    if: github.repository == 'ion-fusion/fusion-java'

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: corretto

    # Generates and submits a dependency graph, enabling Dependabot Alerts.
    # https://github.com/gradle/actions/blob/main/dependency-submission
    # https://github.com/gradle/github-dependency-submission-demo
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
