# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# This workflow will:
#   * build the project with Gradle
#   * upload its dependency graph to workflow artifact storage
#
# The "PR Submit Dependency Graph" workflow triggers when this one completes.

name: PR Build and Record Dependencies

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read # 'write' permission is not available

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    # https://github.com/actions/setup-java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: corretto

    # Configure Gradle for optimal use in GitHub Actions,
    # including caching of downloaded dependencies.
    # https://github.com/gradle/actions/blob/main/setup-gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle Wrapper
      run: ./gradlew release

  generate-dependency-graph:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: corretto

    - name: Generate dependency graph
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-graph: generate-and-upload
