# Performs a GitHub dependency review on a pull request, based on data inferred by GitHub and/or
# submitted by the "PR Submit Dependency Graph" workflow.
#
# This workflow will:
#   * wait for other workflows triggered by the PR to submit a graph snapshot
#   * analyze the graph using GitHub's Dependency Review API
#
# By default, the dependency review will fail if it discovers any vulnerable packages.
#
# See:
#   * https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review
#   * https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#usage-with-pull-requests-from-public-forked-repositories

name: PR Dependency Review

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: 'Dependency Review'
      uses: actions/dependency-review-action@v4
      with:
        retry-on-snapshot-warnings: true
        # This is the time, in seconds, that the workflow will wait
        # for the graph to be generated by the other workflows.
        # It must be longer than their total expected runtime.
        retry-on-snapshot-warnings-timeout: 600
