name: push-container-images

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
        base:
          - corretto-8
          - temurin-8
          - zulu-8
          - alpine-openjdk-8
          - ubuntu-openjdk-8
          - rhel-openjdk-8

    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Build image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          build-args: |
            BASE=${{ matrix.base }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

